import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Entete from "./components/Entete/Entete";
import Footer from "./components/footer/page";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="w-full flex flex-col min-h-screen">
          <Entete />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
